# Generated by Django 2.1.7 on 2019-03-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20190316_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='ministry_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='ministry_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
