# Generated by Django 2.1.7 on 2019-03-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partner_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='Membership_date',
            new_name='membership_date',
        ),
    ]
