# Generated by Django 2.1.7 on 2019-03-16 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20190316_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='membership_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Date when partner joined', null=True),
        ),
    ]
