# Generated by Django 2.1.7 on 2019-03-20 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partner_address'),
        ('testaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testament',
            name='Partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partners.Partner'),
        ),
    ]
