# Generated by Django 2.1.7 on 2019-03-10 18:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('photo1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo4', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo5', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo6', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
